name: Python CI/CD with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  docker-ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t python-ci-cd-app .

      - name: Run tests inside Docker container
        run: |
          docker run python-ci-cd-app pytest

      - name: Deploy Docker container (Simulation)
        run: |
          echo "Deploying Docker container..."
          docker run -d python-ci-cd-app
